import {
  Aboveit,
  Accenture,
  Arktekk,
  Bekk,
  Bouvet,
  Buypass,
  Capgemini,
  Capra,
  CGI,
  Cloudberries,
  Computas,
  DNB,
  Elastic,
  Embriq,
  Entur,
  Experis,
  Finn,
  Fremtind,
  Gjensidige,
  Google,
  Husbanken,
  Itera,
  Kantega,
  Knowit,
  Kodemaker,
  Miles,
  NAV,
  Netcompany,
  NorskTipping,
  Oslo,
  PolitietPIT,
  PostenBring,
  Protector,
  RedHat,
  SafetyWing,
  Scelto,
  Scienta,
  Skatteetaten,
  SopraSteria,
  Sparebank1,
  Spirgroup,
  SSB,
  StatensVegvesen,
  Statnett,
  Storebrand,
  Systek,
  Techpros,
  Telenor,
  TetDigital,
  Tietoevry,
  Tolletaten,
  Tripletex,
  Twoday,
  Uptime,
  Vaadin,
  Webstep,
} from '../../Assets';
import { FunctionComponent } from 'react';
import { SvgProps } from 'react-native-svg';

interface Partner {
  name: string;
  homepageUrl: string;
  logoUrl: FunctionComponent<SvgProps>;
}

export const partners: Partner[] = [
  { name: 'Aboveit', homepageUrl: 'https://www.aboveit.no', logoUrl: Aboveit },
  { name: 'Accenture', homepageUrl: 'https://www.accenture.com', logoUrl: Accenture },
  { name: 'Arktekk', homepageUrl: 'https://www.arktekk.no', logoUrl: Arktekk },
  { name: 'Bekk', homepageUrl: 'https://www.bekk.no', logoUrl: Bekk },
  { name: 'Bouvet', homepageUrl: 'https://www.bouvet.no', logoUrl: Bouvet },
  { name: 'Buypass', homepageUrl: 'https://www.buypass.no', logoUrl: Buypass },
  { name: 'Capgemini', homepageUrl: 'https://www.capgemini.com', logoUrl: Capgemini },
  { name: 'Capra', homepageUrl: 'https://www.capraconsulting.no', logoUrl: Capra },
  { name: 'CGI', homepageUrl: 'https://www.cgi.com', logoUrl: CGI },
  { name: 'Cloudberries', homepageUrl: 'https://www.cloudberries.no', logoUrl: Cloudberries },
  { name: 'Computas', homepageUrl: 'https://www.computas.com', logoUrl: Computas },
  { name: 'DNB', homepageUrl: 'https://www.dnb.no', logoUrl: DNB },
  { name: 'Elastic', homepageUrl: 'https://www.elastic.co', logoUrl: Elastic },
  { name: 'Embriq', homepageUrl: 'https://www.embriq.no', logoUrl: Embriq },
  { name: 'Entur', homepageUrl: 'https://www.entur.no', logoUrl: Entur },
  { name: 'Experis', homepageUrl: 'https://www.experis.no', logoUrl: Experis },
  { name: 'Finn', homepageUrl: 'https://www.finn.no', logoUrl: Finn },
  { name: 'Fremtind', homepageUrl: 'https://www.fremtind.no', logoUrl: Fremtind },
  { name: 'Gjensidige', homepageUrl: 'https://www.gjensidige.no', logoUrl: Gjensidige },
  { name: 'Google', homepageUrl: 'https://www.google.com', logoUrl: Google },
  { name: 'Husbanken', homepageUrl: 'https://www.husbanken.no', logoUrl: Husbanken },
  { name: 'Itera', homepageUrl: 'https://www.itera.no', logoUrl: Itera },
  { name: 'Kantega', homepageUrl: 'https://www.kantega.no', logoUrl: Kantega },
  { name: 'Knowit', homepageUrl: 'https://www.knowit.no', logoUrl: Knowit },
  { name: 'Kodemaker', homepageUrl: 'https://www.kodemaker.no', logoUrl: Kodemaker },
  { name: 'Miles', homepageUrl: 'https://www.miles.no', logoUrl: Miles },
  { name: 'NAV', homepageUrl: 'https://www.nav.no', logoUrl: NAV },
  { name: 'Netcompany', homepageUrl: 'https://www.netcompany.com', logoUrl: Netcompany },
  { name: 'Norsk Tipping', homepageUrl: 'https://www.norsk-tipping.no', logoUrl: NorskTipping },
  /*   {
        name: "KS Digitale Fellestjenester",
        homepageUrl: "https://ksdif.no/",
        logoUrl: KS
    },
    { name: "Novari IKS", homepageUrl: "https://www.vigoiks.no/", logoUrl: Novari },
 */ { name: 'Oslo', homepageUrl: 'https://www.oslo.kommune.no', logoUrl: Oslo },
  { name: 'Politiet PIT', homepageUrl: 'https://www.politiet.no', logoUrl: PolitietPIT },
  { name: 'Posten Bring', homepageUrl: 'https://www.bring.no', logoUrl: PostenBring },
  { name: 'Protector', homepageUrl: 'https://www.protector.no', logoUrl: Protector },
  { name: 'Red Hat', homepageUrl: 'https://www.redhat.com', logoUrl: RedHat },
  { name: 'SafetyWing', homepageUrl: 'https://www.safetywing.com', logoUrl: SafetyWing },
  { name: 'Scelto', homepageUrl: 'https://www.scelto.no', logoUrl: Scelto },
  { name: 'Scienta', homepageUrl: 'https://www.scienta.no', logoUrl: Scienta },
  { name: 'Skatteetaten', homepageUrl: 'https://www.skatteetaten.no', logoUrl: Skatteetaten },
  { name: 'Sopra Steria', homepageUrl: 'https://www.soprasteria.no', logoUrl: SopraSteria },
  { name: 'Sparebank-1', homepageUrl: 'https://www.sparebank1.no', logoUrl: Sparebank1 },
  { name: 'Spirgroup', homepageUrl: 'https://www.spirgroup.no', logoUrl: Spirgroup },
  { name: 'SSB', homepageUrl: 'https://www.ssb.no', logoUrl: SSB },
  { name: 'Statens Vegvesen', homepageUrl: 'https://www.vegvesen.no', logoUrl: StatensVegvesen },
  { name: 'Statnett', homepageUrl: 'https://www.statnett.no', logoUrl: Statnett },
  { name: 'Storebrand', homepageUrl: 'https://www.storebrand.no', logoUrl: Storebrand },
  { name: 'Systek', homepageUrl: 'https://www.systek.no', logoUrl: Systek },
  { name: 'Techpros', homepageUrl: 'https://www.techpros.no', logoUrl: Techpros },
  { name: 'Telenor', homepageUrl: 'https://www.telenor.no', logoUrl: Telenor },
  { name: 'Tet Digital', homepageUrl: 'https://ruter.no/om-ruter/jobb', logoUrl: TetDigital },
  { name: 'Tietoevry', homepageUrl: 'https://www.tietoevry.com', logoUrl: Tietoevry },
  { name: 'Tolletaten', homepageUrl: 'https://www.toll.no', logoUrl: Tolletaten },
  { name: 'Tripletex', homepageUrl: 'https://www.tripletex.no', logoUrl: Tripletex },
  { name: 'Twoday', homepageUrl: 'https://www.twoday.no', logoUrl: Twoday },
  { name: 'Uptime', homepageUrl: 'https://www.uptimeconsulting.no', logoUrl: Uptime },
  { name: 'Vaadin', homepageUrl: 'https://vaadin.com', logoUrl: Vaadin },
  { name: 'Webstep', homepageUrl: 'https://www.webstep.no', logoUrl: Webstep },
];
